
development:
  adapter: postgresql
  database: cookbook_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: cookbook_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: cookbook_prod
  pool: 5
  timeout: 5000

